VC: Fix java.lang.ArrayIndexOutOfBoundsException issue
In current state machine design, there could be timing issue issue to cause
java.lang.ArrayIndexOutOfBoundsException: index=-1, when state transition exit
one state to enter another state.
at this timing, the mStateStackTopIndex value of mStateStack be set to -1.

Fix: check mCurrentConnectionState maintained in VC state machine to avoid
calling getCurrentState to cause AndroidRuntime exception.

CRs-Fixed: 4078843
Change-Id: Ib1e5c1fda05be75cd1bb013ab68a32369696fea7